name: will-prod CICD

on:
  pull_request:
    branches:
      - will-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
      - name: Install packages from requirements.txt
        working-directory: ./projects/jaffle_shop-will
        run: |
          pip3 install -r requirements.txt
      - name: Run dbt compile
        working-directory: ./projects/jaffle_shop-will
        run: |
          dbt compile 
      - name: Run dbt deps and required tests
        working-directory: ./projects/jaffle_shop-will
        run: |
          dbt deps
          dbt run-operation required_tests

