yaml
name: will-prod CICD
on:
  pull_request:
    branches:
      - will-prod

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10.5
      with:
        python-version: '3.10.5'
    - name: Install dependencies
      run: pip3 install -r requirements.txt

