name: will-prod CICD

on:
  pull_request:
    branches:
      - will-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
      - name: Switch to jaffle_shop-will
        run: cd projects/jaffle_shop-will
      - name: Install dependencies
        run: pwd; pip3 install -r requirements.txt