jaffle_shop:
  target: dev
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: jaffle-shop-will-dev-b917b7f83e97.json
      location: US
      method: service-account
      priority: interactive
      project: jaffle-shop-will-dev
      threads: 4
      type: bigquery

      # for dbt Python models to be run on Dataproc Serverless
      gcs_bucket: dbt-python
      dataproc_region: us-central1
      submission_method: serverless

    prod:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt-service-keyfile
      location: US
      method: service-account
      priority: interactive
      project: jaffle-shop-will-prod
      threads: 4
      type: bigquery